# Generated by Django 4.1.7 on 2023-04-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_post_user_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('politics', 'Politics'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('business', 'Business'), ('economy', 'Economy'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='timeStamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
